package net.iyun.originsunedibles.item;

import net.minecraft.item.FoodComponent;

public class FoodControl {
    public static final FoodComponent COAL = new FoodComponent.Builder().hunger(4).saturationModifier(1.2f).build();
    public static final FoodComponent CHARCOAL = new FoodComponent.Builder().hunger(3).saturationModifier(1.1f).build();
    public static final FoodComponent DIAMOND = new FoodComponent.Builder().hunger(8).saturationModifier(1.2f).build();
    public static final FoodComponent EMERALD = new FoodComponent.Builder().hunger(3).saturationModifier(1.2f).build();
    public static final FoodComponent LAPIS = new FoodComponent.Builder().hunger(2).saturationModifier(.6f).build();
    public static final FoodComponent REDSTONE = new FoodComponent.Builder().hunger(2).saturationModifier(.6f).build();
    public static final FoodComponent LEATHER = new FoodComponent.Builder().hunger(4).saturationModifier(.5f).build();
    public static final FoodComponent RAWIRON = new FoodComponent.Builder().hunger(4).saturationModifier(.6f).build();
    public static final FoodComponent RAWGOLD = new FoodComponent.Builder().hunger(3).saturationModifier(.75f).build();
    public static final FoodComponent RAWCOPPER = new FoodComponent.Builder().hunger(3).saturationModifier(.5f).build();
    public static final FoodComponent AMETHYSTSHARD = new FoodComponent.Builder().hunger(3).saturationModifier(.5f).build();
    public static final FoodComponent BOWL = new FoodComponent.Builder().hunger(3).saturationModifier(.5f).build();
    public static final FoodComponent COPPER_INGOT = new FoodComponent.Builder().hunger(4).saturationModifier(.5f).build();
    public static final FoodComponent GOLD_INGOT = new FoodComponent.Builder().hunger(4).saturationModifier(.5f).build();
    public static final FoodComponent IRON_INGOT = new FoodComponent.Builder().hunger(3).saturationModifier(.5f).build();
    public static final FoodComponent NETH_INGOT = new FoodComponent.Builder().hunger(7).saturationModifier(.8f).build();
    public static final FoodComponent NETH_SCRAP = new FoodComponent.Builder().hunger(5).saturationModifier(.6f).build();
    public static final FoodComponent GOLD_NUG = new FoodComponent.Builder().hunger(2).saturationModifier(.25f).snack().build();
    public static final FoodComponent IRON_NUG = new FoodComponent.Builder().hunger(2).saturationModifier(.25f).snack().build();
    public static final FoodComponent QUARTZ = new FoodComponent.Builder().hunger(3).saturationModifier(.25f).snack().build();
    public static final FoodComponent BONE = new FoodComponent.Builder().hunger(4).saturationModifier(.25f).snack().build();
    public static final FoodComponent BONEMEAL = new FoodComponent.Builder().hunger(2).saturationModifier(.5f).snack().build();
    public static final FoodComponent EGG = new FoodComponent.Builder().hunger(3).saturationModifier(.5f).snack().build();
    public static final FoodComponent FEATHER = new FoodComponent.Builder().hunger(4).saturationModifier(.5f).snack().build();
    public static final FoodComponent FLINT = new FoodComponent.Builder().hunger(4).saturationModifier(.5f).build();
    public static final FoodComponent SNOWBALL = new FoodComponent.Builder().hunger(1).saturationModifier(.5f).snack().build();
    public static final FoodComponent STICK = new FoodComponent.Builder().hunger(1).saturationModifier(.5f).snack().build();
    public static final FoodComponent STRING = new FoodComponent.Builder().hunger(1).saturationModifier(.5f).snack().build();
    public static final FoodComponent WHEAT = new FoodComponent.Builder().hunger(2).saturationModifier(.5f).build();
    public static final FoodComponent WHEATSEEDS = new FoodComponent.Builder().hunger(2).saturationModifier(.5f).snack().build();
    public static final FoodComponent CLAYBALL = new FoodComponent.Builder().hunger(4).saturationModifier(.5f).snack().build();
    public static final FoodComponent GSACKINK = new FoodComponent.Builder().hunger(6).saturationModifier(.5f).build();
    public static final FoodComponent SACKINK = new FoodComponent.Builder().hunger(5).saturationModifier(.5f).build();
    public static final FoodComponent PRISMASHARD = new FoodComponent.Builder().hunger(4).saturationModifier(.5f).build();
    public static final FoodComponent PRISMACRYSTAL = new FoodComponent.Builder().hunger(4).saturationModifier(.5f).build();
    public static final FoodComponent RABBITFOOT = new FoodComponent.Builder().hunger(5).saturationModifier(.5f).build();
    public static final FoodComponent RABBITHIDE = new FoodComponent.Builder().hunger(5).saturationModifier(.5f).build();
    public static final FoodComponent SCUTE = new FoodComponent.Builder().hunger(5).saturationModifier(.5f).build();
    public static final FoodComponent SLIMEBALL = new FoodComponent.Builder().hunger(3).saturationModifier(.5f).snack().build();
    public static final FoodComponent HONEYCOMB = new FoodComponent.Builder().hunger(6).saturationModifier(.5f).build();
    public static final FoodComponent BLAZEROD = new FoodComponent.Builder().hunger(4).saturationModifier(1f).build();
    public static final FoodComponent ENDEREYE = new FoodComponent.Builder().hunger(4).saturationModifier(1f).build();
    public static final FoodComponent ENDERPEARL = new FoodComponent.Builder().hunger(4).saturationModifier(1f).build();
    public static final FoodComponent FIRECHARGE = new FoodComponent.Builder().hunger(7).saturationModifier(.5f).build();
    public static final FoodComponent HEARTSEA = new FoodComponent.Builder().hunger(8).saturationModifier(1f).build();
    public static final FoodComponent NAUTSHELL = new FoodComponent.Builder().hunger(5).saturationModifier(1f).build();
    public static final FoodComponent NETHSTAR = new FoodComponent.Builder().hunger(6).saturationModifier(1f).build();
    public static final FoodComponent SHULKSHELL = new FoodComponent.Builder().hunger(4).saturationModifier(.5f).build();
    public static final FoodComponent POPPEDCHORUS = new FoodComponent.Builder().hunger(5).saturationModifier(.5f).build();
    public static final FoodComponent BAMBOO = new FoodComponent.Builder().hunger(3).saturationModifier(.5f).snack().build();
    public static final FoodComponent BEETSEEDS = new FoodComponent.Builder().hunger(4).saturationModifier(.5f).snack().build();
    public static final FoodComponent BOOK = new FoodComponent.Builder().hunger(5).saturationModifier(.5f).build();
    public static final FoodComponent BRICK = new FoodComponent.Builder().hunger(4).saturationModifier(.5f).build();
    public static final FoodComponent ECHO = new FoodComponent.Builder().hunger(6).saturationModifier(.5f).build();
    public static final FoodComponent TEAR = new FoodComponent.Builder().hunger(6).saturationModifier(.5f).build();
    public static final FoodComponent BOTTLE = new FoodComponent.Builder().hunger(3).saturationModifier(.5f).build();
    public static final FoodComponent GDUST = new FoodComponent.Builder().hunger(3).saturationModifier(.5f).build();
    public static final FoodComponent KELP = new FoodComponent.Builder().hunger(1).snack().saturationModifier(.5f).build();
    public static final FoodComponent CREAM = new FoodComponent.Builder().hunger(3).snack().saturationModifier(.5f).build();
    public static final FoodComponent MELONS = new FoodComponent.Builder().hunger(3).snack().saturationModifier(.5f).build();
    public static final FoodComponent NETHBRICK = new FoodComponent.Builder().hunger(4).saturationModifier(.5f).build();
    public static final FoodComponent WART = new FoodComponent.Builder().hunger(4).saturationModifier(.5f).build();
    public static final FoodComponent PAPER = new FoodComponent.Builder().hunger(4).saturationModifier(.5f).build();
    public static final FoodComponent MEMBRANE = new FoodComponent.Builder().hunger(4).saturationModifier(.5f).build();
    public static final FoodComponent PITCH = new FoodComponent.Builder().hunger(7).saturationModifier(.5f).build();
    public static final FoodComponent PUMPS = new FoodComponent.Builder().hunger(3).snack().saturationModifier(.5f).build();
    public static final FoodComponent CANE = new FoodComponent.Builder().hunger(3).saturationModifier(.5f).build();
    public static final FoodComponent TURTEGG = new FoodComponent.Builder().hunger(3).saturationModifier(.5f).build();

}
